# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-rauc-bbb"
BBFILE_PATTERN_meta-rauc-bbb = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-rauc-bbb = "6"

LAYERDEPENDS_meta-rauc-bbb = "core rauc yoctobsp"
LAYERSERIES_COMPAT_meta-rauc-bbb = "scarthgap"

RAUC_KEY_FILE ?= "${LAYERDIR}/files/rauc-example-keys/development-1.key.pem"
RAUC_CERT_FILE ?= "${LAYERDIR}/files/rauc-example-keys/development-1.cert.pem"
RAUC_KEYRING_FILE ?= "${LAYERDIR}/files/rauc-example-keys/ca.cert.pem"
