beaglebone.conf
	require conf/machine/include/ti33x.inc
		require conf/machine/include/ti-soc.inc
			require conf/machine/include/soc-family.inc
		require conf/machine/include/arm/armv7a/tune-cortexa8.inc
			require conf/machine/include/arm/arch-armv7a.inc
				require conf/machine/include/arm/arch-armv6.inc
					require conf/machine/include/arm/arch-armv5-dsp.inc
						require conf/machine/include/arm/arch-armv5.inc
							require conf/machine/include/arm/arch-armv4.inc
								require conf/machine/include/arm/arch-arm.inc
								require conf/machine/include/arm/feature-arm-thumb.inc
							require conf/machine/include/arm/feature-arm-vfp.inc
				require conf/machine/include/arm/feature-arm-neon.inc
				require conf/machine/include/arm/feature-arm-simd.inc
		require conf/machine/include/ti-bsp.inc    ---- virtual/kernel
		require conf/machine/include/mesa-pvr.inc   --- Graphics


======
TODO: wirte secribtion for each file


require conf/machine/include/ti33x.inc
==================================================================


require conf/machine/include/ti-soc.inc
==================================================================


require conf/machine/include/soc-family.inc
==================================================================


require conf/machine/include/arm/armv7a/tune-cortexa8.inc
==================================================================


require conf/machine/include/arm/arch-armv7a.inc
==================================================================


require conf/machine/include/arm/arch-armv6.inc
==================================================================


require conf/machine/include/arm/arch-armv5-dsp.inc
==================================================================


require conf/machine/include/arm/arch-armv5.inc
==================================================================


require conf/machine/include/arm/arch-armv4.inc
==================================================================


require conf/machine/include/arm/arch-arm.inc
==================================================================


require conf/machine/include/arm/feature-arm-thumb.inc
==================================================================


require conf/machine/include/arm/feature-arm-vfp.inc
==================================================================


require conf/machine/include/arm/feature-arm-neon.inc
==================================================================


require conf/machine/include/arm/feature-arm-simd.inc
==================================================================


require conf/machine/include/ti-bsp.inc    ---- virtual/kernel
==================================================================


require conf/machine/include/mesa-pvr.inc   --- Graphics
==================================================================

